version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - crypto_network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: my-server
    depends_on:
      - nginx
    ports:
      - "8080:8080"
    volumes:
      - ./bolt.db:/bolt.db
    networks:
      - crypto_network

networks:
  crypto_network:
    driver: bridge