version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    ports:
      - "80:80"
    volumes:
      - ./index.html:/usr/share/nginx/index.html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    networks:
      - my_network

  server:
    # build:
    #   context: ./server
    #   dockerfile: Dockerfile
    image: golang_blockchain-server:latest
    container_name: my-server
    depends_on:
      - nginx
    ports:
      - "8080:8080"
    volumes:
     - ./bolt.db:/bolt.db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.101.0/24